### ISSUE TITLE
Canvas: trying to draw too large bitmap

### ISSUE THREAD

**Issue by the-mskd-dev** [natario1/ZoomLayout#127]
Hello !

First, thank you for your awesome library !

I face to a Runtime Exception : Canvas trying to draw a too large Bitmap.
Below the stack trace I've got : 

`Fatal Exception: java.lang.RuntimeException: Canvas: trying to draw too large(147000000bytes) bitmap.
       at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
       at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:98)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
       at android.widget.ImageView.onDraw(ImageView.java:1360)
       at com.otaliastudios.zoom.ZoomImageView.onDraw(ZoomImageView.kt:120)
       at android.view.View.draw(View.java:20234)
       at android.view.View.updateDisplayListIfDirty(View.java:19109)
       at android.view.View.draw(View.java:19962)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
       at android.view.View.updateDisplayListIfDirty(View.java:19100)
       at android.view.View.draw(View.java:19962)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
       `

Thank you again for your work !

**Comment by sgravel-dev** [comment]
You are trying to allocate ~147MB...  What size is your content?

**Comment by the-mskd-dev** [comment]
I try to load image from storage or internet, with Picasso then with Glide. In this case the photo size is 156ko. Sometimes everything works well, sometimes it crash

**Comment by sgravel-dev** [comment]
That is the compressed size of the image, what are its dimensions?

**Comment by the-mskd-dev** [comment]
Hello, I've found the problem, and it isn't caused by ZoomImageView ! Sorry for this wrong issue, everything is working well ! I close that wrong issue

**Comment by looooker** [comment]
@KevynBct Hi,I have faced the same issue,How did you solve it?

**Comment by the-mskd-dev** [comment]
@looooker Hi, I just use a low res drawable, it seems my drawables are too high, even in a ImageView
