### ISSUE TITLE
Maximum zoom less than minimum

### ISSUE THREAD

**Issue by the-mskd-dev** [natario1/ZoomLayout#129]
Hello,

First thank you for your amazing work.

I'm facing with an issue where apparently the max zoom is less than minimum :

`
Fatal Exception: java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 1.235147 is less than minimum 1.3270956.
    at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1052)
    at com.otaliastudios.zoom.internal.movement.ZoomManager.checkBounds$zoomlayout_release(ZoomManager.kt:121)
    at com.otaliastudios.zoom.internal.matrix.MatrixController.applyUpdate$zoomlayout_release(MatrixController.kt:263)
    at com.otaliastudios.zoom.internal.matrix.MatrixController.applyUpdate$zoomlayout_release(MatrixController.kt:238)
    at com.otaliastudios.zoom.ZoomEngine$Callbacks.onMatrixSizeChanged(ZoomEngine.kt:106)
    at com.otaliastudios.zoom.internal.matrix.MatrixController.onSizeChanged(MatrixController.kt:206)
    at com.otaliastudios.zoom.internal.matrix.MatrixController.setContainerSize$zoomlayout_release(MatrixController.kt:188)
    at com.otaliastudios.zoom.ZoomEngine.setContainerSize(ZoomEngine.kt:568)
    at com.otaliastudios.zoom.ZoomImageView.onSizeChanged(ZoomImageView.kt:111)
    at android.view.View.sizeChange(View.java:21007)
    at android.view.View.setFrame(View.java:20968)
    at android.widget.ImageView.setFrame(ImageView.java:1209)
    at android.view.View.layout(View.java:20828)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1654)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1654)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:754)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2991)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2504)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1635)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7795)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1172)
    at android.view.Choreographer.doCallbacks(Choreographer.java:984)
    at android.view.Choreographer.doFrame(Choreographer.java:809)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1158)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6863)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`

This issue doesn't appear frequently and I don't know why.

Thank you again for your work, and your support,
Have a great day !

**Comment by ycluk** [comment]
I had this issue when I only did setMaxZoom() in the constructor of my class that extends ZoomLayout. After I commented out the setMaxZoom() in my class constructor, the error went away. So I set both min and max zoom in my class's constructor, and this does not happen again.

I "believe" ZoomLayout automatically sets minZoom and maxZoom somewhere. ZoomLayout will set zoom to a large number when there are only few items to be shown on the screen. If I force only set max zoom when ZoomLayout auto set min zoom which is larger than max zoom I set, the app will crash with this exception.

I did only a quick research, and I couldn't find any method to get the zoom at runtime to prevent this issue. If you can live with forcing both min and max zoom at the same time, you can do that. Or make sure the view that your app show will never have min zoom bigger than max zoom.

However, I think it would be best that if the API check at runtime not to set min zoom larger than max zoom. Developers who aren't familiar with the API could only set max zoom and their app will crash like ours.

Hope this help.

**Comment by markusressel** [comment]
@ycluk @KevynBct Is it possible that you tried to change the `maxZoomMode` when using `setMaxZoom()`?

**Comment by ycluk** [comment]
@markusressel I have never worked on this project & issue. I just faced the same error that @KevynBct did when I was working on my own project, so I wanted to share my experience.

I don't know if this can help you, but I fixed my problem by using Zoom APIs `TYPE_ZOOM` instead of `TYPE_REAL_ZOOM`, e.g. `setMaxZoom(1.0f, TYPE_ZOOM)`. `TYPE_REAL_ZOOM` is the actual zoom scale, and I believe... ZoomLayout calculates the real zoom scale automatically somewhere when the view is being drawn.

If anyone set maximum real zoom to a fixed number, and when ZoomLayout calculates real zoom is larger than the set max real zoom, `java.lang.IllegalArgumentException` will occur.

`TYPE_ZOOM` is more like relative zoom, and `TYPE_REAL_ZOOM` is the actual zoom scale, you can put Android log and use Zoom APIs `getZoom()` & `getRealZoom()`, and you will see zoom always starts with 1, and real zoom could be different every time.

If possible whenever `setMaxZoom()` or `setMinZoom()`, I recommend just use `TYPE_ZOOM`, and don't use `TYPE_REAL_ZOOM`.

Hope this help

**Comment by markusressel** [comment]
I just tried it out and its a general problem of being able to set invalid values (min > max) for the zoom limits.

One way to address this would be to merge the `setMaxZoom()` and `setMinZoom()` api methods into a single one, where we can always make sure the passed in values are a valid configuration. This would of course be a breaking change, and also forces the dev to always pass in both values, even if he only wants to change one.

A different approach would be to coerce min and max values when calling either `setMaxZoom()` or `setMinZoom()`, but this could be confusing to developers, since the value they try to set might not be the one that is actually set. This could be avoided by raising an exception instead, but would also lead to cumbersome interactions, forcing the developer to use the `setMaxZoom()` and `setMinZoom()` methods in a specific order, depending on the current values of `minZoom` and `maxZoom`. F.ex. when trying to change from
`min = 2`, `max = 3`  
to  
`min = 4`, `max = 5`  
the dev would have to call `setMaxZoom(5)` first, and then `setMinZoom(4)`.

However, this exception is mainly occurring due to a dev using an invalid max/min configuration, either because `ZOOM` and `REAL_ZOOM` are confusing, or maybe due to other reasons. The question being how we want to deal with this kind of invalid state.

@natario1 Neither of these solutions really appeal to me, any thoughts on that?

EDIT:
Maybe just using a default value for the zoom type (`TYPE_ZOOM`) would also help reduce the confusion.

**Comment by natario1** [comment]
If we had only `REAL_ZOOM` **or** `ZOOM`, then we'd have absolute min/max value that we could check in `setMinZoom` and `setMaxZoom` like you said for example.

But when they are used together (for example, min is a `REAL_ZOOM`, max is a `ZOOM`), the range of accepted values can depend on the transformation values and even the content size. So one (min,max) couple might be valid with the current drawable or transformation, and invalid with the next.

So I think there's no way to check the validity (other than checking in **all** of these entry points, not just setMinZoom and setMaxZoom...) and even if we do it's hard to coerce to a fallback (if we get into the situation where min > max, how do you redefine min and max? You might set either min = max or max = min, but there's no obvious default and it makes a difference).

I feel like crashing is the correct solution, though we should do so with a clear message. I also agree to set a default value to the type with JvmOverloads, so it's less likely that people use `REAL_ZOOM` for one and `ZOOM` for the other.

**Comment by natario1** [comment]
So just to be clear, it's not like ZOOM or REAL_ZOOM is bad, but mixing the two is.

At the same time, both types are useful and it's legit to want to mix them in some cases. For example I might want to use `setMinZoom(1.0, ZOOM)` to say that the image should not be zoomed out. And at the same time, use `setMaxZoom(4.0, REAL_ZOOM)`, to make sure that the bitmap does not get too much pixelated. 

But when one does so, he must be very careful with the size of the content/container and the transformation, because min > max can happen. In the above example, if the image is like 10x10, it must be zoomed a lot for the initial centering/transformation, so when you convert the min `ZOOM` (1.0) to `REAL_ZOOM`, you likely get something bigger than 4.0.

It's an advanced use-case basically. For other usages I think setting a default value for type is a very good idea.

**Comment by ycluk** [comment]
@markusressel I have tried your approach to force both min zoom and max zoom, and it is just like you said, cumbersome. However, I found out I only need to `setMaxZoom(###, TYPE_ZOOM)`, and if I can get the max zoom not to zoom too large, it should be good enough.

@natario1 from what I see in the ZoomLayout API, I don't see we can get min zoom or max zoom value, so there's no way to validate min zoom won't be larger than max zoom. The API only has `getZoom()` & `getRealZoom()` to know the zoom scale at run time. If you know how to get the value of min & max zoom, please kindly share it.

Also to your point not to make the zoom too large to become pixelated, you can use `TYPE_ZOOM` to achieve that, and not touching `TYPE_REAL_ZOOM`. For example, from what I see in Android when the view is drawn `TYPE_ZOOM` always starts at 1.0 as min & 2.5 (default) as max, but `TYPE_REAL_ZOOM` can be at 2.0 as min which means 5.0 as max or 0.5 as min which means 1.25 as max.

In the case of `TYPE_REAL_ZOOM` 0.5 min & 1.25 max is likely to imply the image is large, so the max zoom needs to be increased in order to see detail of the image clearly, but not too pixelated. I would divide 1 by min zoom, 1 / 0.5 = 2, and it's obvious min zoom is half the size of 1, so then I multiply max zoom by (the quotient) 2, and I want the real max zoom to be 2.5 instead of 1.25, but I don't want to set `TYPE_REAL_ZOOM` to avoid min > max problem, so I multiply `TYPE_ZOOM` default max zoom value (2.5) by 2 (2.5 x 2 = 5), then I `setMaxZoom(5.0f, TYPE_ZOOM)`.

The formula I used above is just an example, but you can use `TYPE_ZOOM` to get whatever relative zoom scale you need without using `TYPE_REAL_ZOOM`, and this way can avoid min > max real zoom problem. However, this could still be confusing to developers who aren't familiar with the API.

Also, there is no way to `getRealZoom()` until the view is drawn, I tried `getRealZoom()` in Android `onStart()` and it didn't return anything, so I had a button in my app to recalculate the max zoom and set it, but I am not that can be a solution to this problem.

**Comment by markusressel** [comment]
@ycluk 
>  I have tried your approach to force both min zoom and max zoom, and it is just like you said, cumbersome.

I am not sure what you mean, since currently there is no need for this if you set both min and max. It would be cumbersome if we added a check and threw additional exceptions, which we currently don't.

@natario1 
> But when they are used together (for example, min is a REAL_ZOOM, max is a ZOOM), the range of accepted values can depend on the transformation values and even the content size. So one (min,max) couple might be valid with the current drawable or transformation, and invalid with the next.

I still feel like this (if it works depends on many different things) will generate a lot of problems on the dev side going forward, even for relatively simple use cases, which is why I think it should be handled at least in some way by the library, even if it is a biased solution. This would give most users a working solution out of the box and when the default solution doesn't fit the expectations of the dev it would still be possible to override it by doing manual calculations with all of the necessary values and using the `setMax/setMin` methods with appropriate values.

> So I think there's no way to check the validity (other than checking in all of these entry points, not just setMinZoom and setMaxZoom...) and even if we do it's hard to coerce to a fallback (if we get into the situation where min > max, how do you redefine min and max? You might set either min = max or max = min, but there's no obvious default and it makes a difference).

Since the problem only occurs when mixing `ZOOM` and `REAL_ZOOM`, and `REAL_ZOOM` is calculated per drawable, I would expect the default behavior to align the `REAL_ZOOM` value to the `ZOOM` value if they don't represent a valid range.

> But when one does so, he must be very careful with the size of the content/container and the transformation, because min > max can happen. In the above example, if the image is like 10x10, it must be zoomed a lot for the initial centering/transformation, so when you convert the min ZOOM (1.0) to REAL_ZOOM, you likely get something bigger than 4.0.

In this case f.ex., the image would have already exceeded the `REAL_ZOOM` limit and thus it would not make sense to allow any scaling at all. Of course this is my opinion on the matter and a different use case might see this different. But imho it would suffice as a default behavior to provide that is useful in most situations and can be customized (by doing a lot of work on the dev side) for others.

So my suggestions would be:
* add `TYPE_ZOOM` as default value to the API method to reduce usage of `TYPE_REAL_ZOOM`
* when min and max are of the same zoom type, don't do anything (maybe add a better error message), the dev has done something "stupid"
* when min is `TYPE_ZOOM` and max is `TYPE_REAL_ZOOM`
    * when the calculated max is less than min, use fallback to min
* when min is `TYPE_REAL_ZOOM` and max is `TYPE_ZOOM`
    * when the calculated max is less than min, use fallback to max

Note that these fallbacks are only meant to be in effect temporarily, to avoid raising an exception. The values set by the dev for min/max should never be changed.

**Comment by markusressel** [comment]
@natario1 any thoughts on my proposal? I would like to implement this (to any extent you prefer) and create a new release after that.

**Comment by natario1** [comment]
Sounds good @markusressel . Your last two points basically mean `when there is a conflict, fallback to the one that is TYPE_ZOOM` right? Also let's Log.w some message in this case.

**Comment by markusressel** [comment]
@natario1 correct, thats probably a better way to describe it :D
