### ISSUE TITLE
Getting error of "java.lang.RuntimeException: ZoomLayout must be used with fixed dimensions (e.g. match_parent)"

### ISSUE THREAD

**Issue by LidorPrototype** [natario1/ZoomLayout#194]
### Describe the bug
I'm using the ZoomLayout inside a ScrollView, and inside the ZoomLayout I have a TextView
when ever I start the app it crashes immidiatley duo to this error:
         java.lang.RuntimeException: ZoomLayout must be used with fixed dimensions (e.g. match_parent)
but I tried putting the ZoomLayout and the ScrollView and the TextView to math_parent on width and height but
still I get the same error.

### Logs
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.l_es.countryplaylist, PID: 24508
    java.lang.RuntimeException: ZoomLayout must be used with fixed dimensions (e.g. match_parent)
        at com.otaliastudios.zoom.ZoomLayout.onMeasure(ZoomLayout.kt:121)
        at android.view.View.measure(View.java:26411)
        at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:2365)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.widget.ScrollView.onMeasure(ScrollView.java:691)
        at android.view.View.measure(View.java:26411)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:792)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:480)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measureChildren(BasicMeasure.java:134)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:277)
        at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:119)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1578)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1690)
        at android.view.View.measure(View.java:26411)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:26411)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:26411)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:26411)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:26411)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1050)
        at android.view.View.measure(View.java:26411)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3638)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2373)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2665)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:732)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```

### Version
Latest ( 1.8.0 )

**Comment by markusressel** [comment]
I really don't get why so many people try to wrap scrollable views inside other scrollable views... most of the time it is bad UX and it causes bugs like this. ZoomLayout needs to know the size of the content at initialization to be able to render properly. I guess the ScrollView messes up the content view size and things break. I'm sorry but you are on your own on this, since this is really not a supported use case.

**Comment by LidorPrototype** [comment]
does the ZoomLayout is also a scrollable view?
I can use just just it without need for the vertical scrollview?

**Comment by markusressel** [comment]
ZoomLayout allows pinch-to-zoom and pan in every direction. When the content is zoomed you can scroll horizontal as well as vertical. Its just like an image viewer, where you can zoom in and pan around the image in both vertical and horizontal direction.

**Comment by LidorPrototype** [comment]
if the content is not zoomed, can he still scroll vertically?

**Comment by markusressel** [comment]
I don't understand your use case without more info, so I can only answer from my existing knowledge. There is little value in being able to scroll to a location where no additional content can be displayed. ZoomLayout has the concept of "overscroll" which allows the user to temporarily scroll over the content bounds.

But before we dive deeper here, please, **read the documentation**, or just try it out on your emulator/device and see for yourself if it works for you. If it doesn't you can always change it yourself (its open source) or ask a question about adding a feature that would benefit the general audience. Of course we would also love to hear back from you if you managed to implement some feature that you want to share via pull request.
